### ISSUE TITLE
Merge extracted images

### ISSUE THREAD

**Issue by turb1te** [superr/splituapp#2]
Hi!

Is it possible to merge extracted img files into UPDATE.APP file?

My idea is to patch boot.img with Magisk and install the UPDATE.APP file. I still haven't been able to unlock my bootloader.

Thanks!

(Sorry for my bad English)

**Comment by superr** [comment]
Hello.

There may be a tool for rebuilding UPDATE.APP. This tool however, does the opposite. It unpacks UPDATE.APP.

Good luck on your journey :)
